# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://miguelpaz.github.io
baseurl: 
title: Miguel Paz
author: Miguel Paz
description: Courses, tools, tutorial, classes, events and other stuff
avatar: profile.jpg
email: miguel.paz@journalism.cuny.edu
github: miguelpaz # username
twitter: miguelpaz
linkedin: miguelpaz
stackoverflow: #username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: #username
google_analytics: #UA-69391421-1


# needed for travis-ci build
#exclude: [vendor]
